org: rafiqueacudjoe
app: test-weather-functions
service: test-weather-functions

frameworkVersion: '2 || 3'

plugins:
  - serverless-offline

useDotenv: true

package:
  individually: true
  excludeDevDependencies: true
  exclude:
    - "!**/.vscode/**"
    - "!**/package-lock.json"
    - "!node_modules/aws-sdk/**"

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'
  region: eu-central-1
  httpApi:
    cors: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - secretsmanager:GetSecretValue
      Resource: "*"

    - Effect: Allow
      Action:
        - AWSLambdaVPCAccessExecutionRole
      Resource: arn:aws:iam::210712744793:role/lambda-vpc-role


functions:
  # lambda to get weather details
  testWeather:
    handler: lambdas/openweather/index.handler
    description: express lambda open weather test
    environment:
      REDIS_HOST: weather-001.yo10re.0001.use1.cache.amazonaws.com
      REDIS_PORT: 6379
     
    package:
      patterns:
        - '!**/lambdas'
        - '**/lambdas/openweather/**'
    events:
      - httpApi: '*'

